### ISSUE TITLE
Collection save not working

### ISSUE THREAD

**Issue by daya-cd** [ginetta/cockpit-sdk#2]
Hello thanks for amazing SDK do you have working example of the collectionSave pls ?

  var data={name:'name11',text:'testdata'};
 cockpit1.collectionSave("test",data).then(data => console.log(data));

having unauthorised error thrown.

**Comment by brunnolou** [comment]
Hey good to know.

Your example is correct, you need to make sure that either the collection has a **`Create entries`** permission or using a **`Full access API-key`**

![image](https://user-images.githubusercontent.com/2729225/35799784-c7083666-0a5e-11e8-8eb7-27b7bad895b1.png)

![image](https://user-images.githubusercontent.com/2729225/35799867-13ef87ea-0a5f-11e8-97ac-3fe5e8e1cc35.png)

Let me know if that works.

**Comment by daya-cd** [comment]
Hi,
Thanks for the prompt reply. 

I am using full API access key also tried to give create entries permission individual to the collection. 
 " Error - Path not found 401 unauthorized "
Still getting this as an issue. 

Thanks
Daya

**Comment by daya-cd** [comment]
Finally solved it is the problem with API key in cms. Full API key doesn't work 

https://github.com/agentejo/cockpit/issues/634

**Comment by brunnolou** [comment]
Cool! 👍  I'm closing this.
