### ISSUE TITLE
support cockpit singleton

### ISSUE THREAD

**Issue by mares29** [ginetta/cockpit-sdk#7]
Hi, do you plan to add support for new cockpit singleton? ;) thx

**Comment by nickhartjes** [comment]
I added the support for singleton, and made a pull request.
https://github.com/ginetta/cockpit-sdk/pull/8

If you want it directly, you can check out my repo:
https://github.com/nickhartjes/cockpit-sdk

**Comment by jankal** [comment]
@brunnolou @mares29 this can be closed as #8 was merged.
